### PR TITLE
Fix ProtocolCodeBasedDecoder memory leak

### PR DESCRIPTION
**Pull request by JoeCqupt**
reproduce code
```
    @Test
    public void testDecodeIllegalPacket2() {
        EmbeddedChannel channel = new EmbeddedChannel();
        ProtocolCodeBasedDecoder decoder = new ProtocolCodeBasedDecoder(1);
        channel.pipeline().addLast(decoder);

        ByteBuf byteBuf = ByteBufAllocator.DEFAULT.buffer(8);
        byteBuf.writeByte((byte) 13);

        int readerIndex = byteBuf.readerIndex();
      
        Assert.assertEquals(0, readerIndex);
        Exception exception = null;
        try {
            channel.writeInbound(byteBuf);
        } catch (Exception e) {
            // ignore
            exception = e;
        }
        Assert.assertNotNull(exception);
        Assert.assertTrue(byteBuf.refCnt() == 0);
    }
```

when `ProtocolCodeBasedDecoder#decode()` throw exception . ByteBuf param  not released

## Summary by CodeRabbit

- **New Features**
	- Enhanced error handling for decoding processes, improving robustness against unexpected input.
	- Introduced a new test case to improve coverage for decoder interactions with illegal packets.

- **Bug Fixes**
	- Ensured consistent state of the buffer after exception handling during decoding operations.

### CODE REVIEW

**Comment by JoeCqupt** [comment]
这个CI好像有毒，线下跑的单测一点问题没有，CI跑就报错
线下：
image
CI：
https://github.com/sofastack/sofa-bolt/actions/runs/10111851447/job/27964641532?pr=355#step:5:1442
image

**Comment by funky-eyes** [comment]
> 这个CI好像有问题，线下跑的单测一点问题没有，CI跑就报错 线下： image CI： https://github.com/sofastack/sofa-bolt/actions/runs/10111851447/job/27964641532?pr=355#step:5:1442 image

我跟你有相同的问题

**Comment by JoeCqupt** [comment]
@chuailiwu

**Comment by JoeCqupt** [comment]
> Hi, @JoeCqupt , I doubt if it is a bug of bolt. ByteBuf will be released at `channelInactive` method. I think you need to check in what condition (such as you encounter an exception when decoding but not close the connection ) you did not invoke this method.

yep. you are right. 
This modification is optional

**Pull request closed without merging**
