### PR TITLE
fix AbstractLifeCycle concurrency problem Fixes gh-163

### PR DESCRIPTION
**Pull request by lollapalooza1989**
fix AbstractLifeCycle concurrency problem Fixes gh-163

### CODE REVIEW

**Comment by lollapalooza1989** [comment]
@dbl-x  can anyone help to slove build problem?

**Comment by khotyn** [comment]
@dbl-x 因为 #177 没有合并的原因？好像最近几个 PR 都 Fail 了。

**Comment by khotyn** [comment]
@lollapalooza1989 You can try to merge the latest master in to your branch and push, the CI should  have fixed.

**Comment by lollapalooza1989** [comment]
@khotyn  I reopen it,now CI was passed.

**Pull request merged**
